create table expense_claims (
     claim_id number (6,0) generated by default as identity (start with 1 cache 20) not null
   , empno number (4,0)
   , purpose varchar2(40)
   , status varchar2(10)
   , total number (8,2)
   , claim_date date
   , approved_by number (4,0)
   , approved_date date
   , payment_date date 
   , approver_notes varchar2(2000)
);

alter table expense_claims add constraint claim_pk primary key (claim_id);

alter table expense_claims add constraint claim_emp_fk foreign key (empno) 
   references emp (empno)
   on delete cascade;

alter table expense_claims add constraint claim_mgr_fk foreign key (approved_by) 
   references emp (empno)
   on delete cascade;

create table expense_items (
     item_id number generated by default as identity (start with 1 cache 20) not null
   , item_claim_id number (6,0)
   , item_date date
   , item_name varchar2(40)
   , item_amount number (6,2)
);

alter table expense_items add constraint item_pk primary key (item_id)

alter table expense_items add constraint item_fk foreign key (claim_id) 
   references  expense_claims(claim_id)
   on delete cascade;

